#!/bin/bash
#
# PolymarketBot - One-Command Deployment Script
#
# This script sets up everything needed to run PolymarketBot on a fresh VPS.
# Optimized for low-latency trading from Amsterdam/Frankfurt/Dublin.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/yourusername/polymarketbot/main/deploy.sh | bash
#
# Or clone and run:
#   git clone https://github.com/yourusername/polymarketbot.git
#   cd polymarketbot
#   chmod +x deploy.sh
#   ./deploy.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    PolymarketBot Deployer                        ║"
echo "║              Low-Latency Copy Trading System                     ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${YELLOW}Warning: Running as root. Consider using a non-root user.${NC}"
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    VERSION=$VERSION_ID
else
    OS=$(uname -s)
    VERSION=$(uname -r)
fi

echo -e "${GREEN}Detected OS:${NC} $OS $VERSION"

# Configuration
INSTALL_DIR="${POLYBOT_INSTALL_DIR:-$HOME/polymarketbot}"
PORT="${PORT:-8765}"
USE_DOCKER="${USE_DOCKER:-auto}"

echo -e "${GREEN}Install directory:${NC} $INSTALL_DIR"
echo -e "${GREEN}Dashboard port:${NC} $PORT"
echo ""

# Function to install Docker
install_docker() {
    echo -e "${BLUE}Installing Docker...${NC}"

    if command -v docker &> /dev/null; then
        echo -e "${GREEN}Docker already installed.${NC}"
        return 0
    fi

    # Install Docker using official script
    curl -fsSL https://get.docker.com | sh

    # Add current user to docker group
    if [ "$EUID" -ne 0 ]; then
        sudo usermod -aG docker $USER
        echo -e "${YELLOW}Added $USER to docker group. You may need to log out and back in.${NC}"
    fi

    # Start Docker service
    sudo systemctl enable docker
    sudo systemctl start docker

    echo -e "${GREEN}Docker installed successfully.${NC}"
}

# Function to install Python dependencies directly
install_python() {
    echo -e "${BLUE}Setting up Python environment...${NC}"

    # Install Python if needed
    if ! command -v python3 &> /dev/null; then
        echo "Installing Python..."
        if command -v apt-get &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip python3-venv
        elif command -v yum &> /dev/null; then
            sudo yum install -y python3 python3-pip
        elif command -v dnf &> /dev/null; then
            sudo dnf install -y python3 python3-pip
        else
            echo -e "${RED}Could not install Python. Please install manually.${NC}"
            exit 1
        fi
    fi

    # Create virtual environment
    cd "$INSTALL_DIR"
    python3 -m venv venv
    source venv/bin/activate

    # Upgrade pip and install dependencies
    pip install --upgrade pip
    pip install -r requirements.txt

    echo -e "${GREEN}Python environment ready.${NC}"
}

# Function to optimize system for trading
optimize_system() {
    echo -e "${BLUE}Optimizing system for low-latency trading...${NC}"

    if [ "$EUID" -eq 0 ] || sudo -n true 2>/dev/null; then
        # Create comprehensive TCP optimization config
        cat << 'EOF' | sudo tee /etc/sysctl.d/99-polymarketbot.conf > /dev/null
# PolymarketBot - Low-Latency Trading Optimizations
# Generated by deploy.sh

# ===== TCP Buffer Sizes =====
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576
net.ipv4.tcp_rmem = 4096 1048576 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# ===== TCP Optimization =====
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fastopen = 3
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65535

# ===== Congestion Control (BBR) =====
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# ===== Keepalive =====
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6

# ===== Timestamps & SACK =====
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1

# ===== Memory =====
net.ipv4.tcp_max_syn_backlog = 65535
net.ipv4.tcp_max_tw_buckets = 2000000
EOF

        # Apply immediately
        sudo sysctl -p /etc/sysctl.d/99-polymarketbot.conf 2>/dev/null || true

        # Verify BBR is active
        if sysctl net.ipv4.tcp_congestion_control 2>/dev/null | grep -q bbr; then
            echo -e "${GREEN}TCP BBR congestion control enabled.${NC}"
        else
            echo -e "${YELLOW}BBR not available (kernel may not support it).${NC}"
        fi

        echo -e "${GREEN}System optimizations applied.${NC}"
    else
        echo -e "${YELLOW}Skipping system optimizations (requires sudo).${NC}"
    fi
}

# Function to setup basic security
setup_security() {
    echo -e "${BLUE}Setting up basic security...${NC}"

    if [ "$EUID" -eq 0 ] || sudo -n true 2>/dev/null; then
        # Install and enable UFW if not already
        if ! command -v ufw &> /dev/null; then
            sudo apt-get install -y ufw 2>/dev/null || true
        fi

        if command -v ufw &> /dev/null; then
            sudo ufw default deny incoming 2>/dev/null || true
            sudo ufw default allow outgoing 2>/dev/null || true
            sudo ufw allow ssh 2>/dev/null || true
            sudo ufw allow ${PORT}/tcp 2>/dev/null || true
            sudo ufw --force enable 2>/dev/null || true
            echo -e "${GREEN}Firewall configured (SSH + port ${PORT}).${NC}"
        fi

        # Install fail2ban if not already
        if ! command -v fail2ban-client &> /dev/null; then
            sudo apt-get install -y fail2ban 2>/dev/null || true
            sudo systemctl enable fail2ban 2>/dev/null || true
            sudo systemctl start fail2ban 2>/dev/null || true
            echo -e "${GREEN}Fail2ban installed and enabled.${NC}"
        fi

        # Set proper permissions on config files
        if [ -f "$INSTALL_DIR/ghost_state.json" ]; then
            chmod 600 "$INSTALL_DIR/ghost_state.json" 2>/dev/null || true
        fi
        if [ -f "$INSTALL_DIR/proxy_config.json" ]; then
            chmod 600 "$INSTALL_DIR/proxy_config.json" 2>/dev/null || true
        fi

        echo -e "${GREEN}Basic security configured.${NC}"
    else
        echo -e "${YELLOW}Skipping security setup (requires sudo).${NC}"
    fi
}

# Function to create systemd service
create_systemd_service() {
    echo -e "${BLUE}Creating systemd service...${NC}"

    if [ "$EUID" -eq 0 ] || sudo -n true 2>/dev/null; then
        cat << EOF | sudo tee /etc/systemd/system/polymarketbot.service > /dev/null
[Unit]
Description=PolymarketBot Copy Trading System
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$INSTALL_DIR
Environment=PORT=$PORT
ExecStart=$INSTALL_DIR/venv/bin/python run_ghost_mode.py
Restart=always
RestartSec=5

# Security hardening
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

        sudo systemctl daemon-reload
        sudo systemctl enable polymarketbot

        echo -e "${GREEN}Systemd service created.${NC}"
        echo -e "${YELLOW}Start with: sudo systemctl start polymarketbot${NC}"
    else
        echo -e "${YELLOW}Skipping systemd service (requires sudo).${NC}"
    fi
}

# Clone or update repository
setup_repository() {
    echo -e "${BLUE}Setting up repository...${NC}"

    if [ -d "$INSTALL_DIR/.git" ]; then
        echo "Updating existing installation..."
        cd "$INSTALL_DIR"
        git pull
    elif [ -d "$INSTALL_DIR" ]; then
        echo "Directory exists, using existing files..."
        cd "$INSTALL_DIR"
    else
        echo "Cloning repository..."
        git clone https://github.com/yourusername/polymarketbot.git "$INSTALL_DIR"
        cd "$INSTALL_DIR"
    fi
}

# Main deployment logic
main() {
    echo -e "${BLUE}Starting deployment...${NC}"
    echo ""

    # Setup repository (skip if we're already in the repo)
    if [ ! -f "run_ghost_mode.py" ]; then
        setup_repository
    else
        INSTALL_DIR=$(pwd)
    fi

    # Optimize system for low-latency trading
    optimize_system

    # Setup basic security (firewall, fail2ban)
    setup_security

    # Check if Docker is preferred/available
    if [ "$USE_DOCKER" = "yes" ] || ([ "$USE_DOCKER" = "auto" ] && command -v docker &> /dev/null); then
        echo -e "${BLUE}Using Docker deployment...${NC}"

        if ! command -v docker &> /dev/null; then
            install_docker
        fi

        # Build and start with Docker Compose
        if command -v docker-compose &> /dev/null; then
            docker-compose up -d --build
        else
            docker compose up -d --build
        fi

        echo ""
        echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${GREEN}║                  Deployment Complete!                            ║${NC}"
        echo -e "${GREEN}╚══════════════════════════════════════════════════════════════════╝${NC}"
        echo ""
        echo -e "Dashboard URL: ${BLUE}http://$(hostname -I | awk '{print $1}'):$PORT${NC}"
        echo -e "              ${BLUE}http://localhost:$PORT${NC}"
        echo ""
        echo -e "Manage with:"
        echo -e "  ${YELLOW}docker compose logs -f${NC}    # View logs"
        echo -e "  ${YELLOW}docker compose restart${NC}    # Restart"
        echo -e "  ${YELLOW}docker compose down${NC}       # Stop"
        echo ""
    else
        echo -e "${BLUE}Using native Python deployment...${NC}"

        # Install Python environment
        install_python

        # Create systemd service
        create_systemd_service

        echo ""
        echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${GREEN}║                  Deployment Complete!                            ║${NC}"
        echo -e "${GREEN}╚══════════════════════════════════════════════════════════════════╝${NC}"
        echo ""
        echo -e "Dashboard URL: ${BLUE}http://$(hostname -I | awk '{print $1}'):$PORT${NC}"
        echo -e "              ${BLUE}http://localhost:$PORT${NC}"
        echo ""
        echo -e "Start the bot:"
        echo -e "  ${YELLOW}cd $INSTALL_DIR${NC}"
        echo -e "  ${YELLOW}source venv/bin/activate${NC}"
        echo -e "  ${YELLOW}python run_ghost_mode.py${NC}"
        echo ""
        echo -e "Or use systemd:"
        echo -e "  ${YELLOW}sudo systemctl start polymarketbot${NC}"
        echo -e "  ${YELLOW}sudo systemctl status polymarketbot${NC}"
        echo ""
    fi

    echo -e "${BLUE}Infrastructure page: http://localhost:$PORT/infrastructure${NC}"
    echo -e "${YELLOW}Configure your proxy settings there for optimal latency.${NC}"
    echo ""
}

# Run main function
main "$@"
